env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
rules: {
  no-restricted-syntax: 0,
  no-await-in-loop: 0,
  guard-for-in: 0,
  no-console: 0,
  global-require: 0,
  no-continue: 0,
  import/no-dynamic-require: 0
}
